# Generated by Django 4.2.5 on 2024-01-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typings', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=100)),
                ('abilities', models.CharField(max_length=30)),
                ('types', models.ManyToManyField(related_name='regions', to='typings.type')),
            ],
        ),
    ]
