# Generated by Django 4.2.5 on 2024-08-05 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monsters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monster',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='monster',
            name='national_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
