# Generated by Django 4.2.5 on 2024-08-27 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typings', '0002_type_creator_alter_typeadvantage_multiplier'),
        ('monsters', '0002_monster_creator_monster_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='date_joined',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='monster',
            name='avg_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='monster',
            name='avg_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.RemoveField(
            model_name='monster',
            name='abilities',
        ),
        migrations.AlterField(
            model_name='monster',
            name='species',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, related_name='monsters', to='typings.type'),
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('effect', models.TextField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='hidden_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_monsters', to='monsters.ability'),
        ),
        migrations.AddField(
            model_name='monster',
            name='abilities',
            field=models.ManyToManyField(blank=True, null=True, related_name='monsters', to='monsters.ability'),
        ),
    ]
