# Generated by Django 4.2.5 on 2024-08-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typings', '0002_type_creator_alter_typeadvantage_multiplier'),
        ('monsters', '0003_rename_date_joined_monster_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='monsters', to='monsters.ability'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='monsters', to='typings.type'),
        ),
    ]
