# Generated by Django 4.2.5 on 2025-02-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('monsters', '0004_alter_monster_abilities_alter_monster_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='creator',
        ),
        migrations.AddField(
            model_name='monster',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monster', to='articles.article'),
        ),
        migrations.AddField(
            model_name='monster',
            name='etymology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
