# Generated by Django 4.2.5 on 2025-02-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0005_remove_monster_creator_monster_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='etymology',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(default='name', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
