# Generated by Django 4.2.5 on 2025-02-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('monsters', '0006_monster_description_alter_monster_etymology_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='creator',
        ),
        migrations.AddField(
            model_name='ability',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability', to='articles.article'),
        ),
    ]
