# Generated by Django 4.2.5 on 2025-02-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0007_remove_ability_creator_ability_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='date_created',
        ),
    ]
