# Generated by Django 4.2.5 on 2025-02-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0001_initial'),
        ('monsters', '0008_remove_monster_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='monsters', to='abilities.ability'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='hidden_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hidden_monsters', to='abilities.ability'),
        ),
        migrations.DeleteModel(
            name='Ability',
        ),
    ]
