# Generated by Django 4.2.5 on 2025-03-17 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0009_alter_monster_abilities_alter_monster_hidden_ability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('from_monster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_monster', to='monsters.monster')),
                ('to_monster_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_monster', to='monsters.monster')),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='evolutions',
            field=models.ManyToManyField(related_name='pre_evolutions', through='monsters.Evolution', to='monsters.monster'),
        ),
    ]
