# Generated by Django 4.2.5 on 2025-03-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0010_evolution_monster_evolutions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolution',
            old_name='from_monster_id',
            new_name='from_monster',
        ),
        migrations.RenameField(
            model_name='evolution',
            old_name='to_monster_id',
            new_name='to_monster',
        ),
    ]
