# Generated by Django 4.2.5 on 2025-03-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0011_rename_from_monster_id_evolution_from_monster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolution',
            name='from_monster',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_monster', to='monsters.monster'),
        ),
        migrations.AlterField(
            model_name='evolution',
            name='to_monster',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_monster', to='monsters.monster'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='evolutions',
            field=models.ManyToManyField(blank=True, related_name='pre_evolutions', through='monsters.Evolution', to='monsters.monster'),
        ),
    ]
