# Generated by Django 4.2.5 on 2025-03-19 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0012_alter_evolution_from_monster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolution',
            name='from_monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_monster', to='monsters.monster'),
        ),
        migrations.AlterField(
            model_name='evolution',
            name='to_monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_monster', to='monsters.monster'),
        ),
    ]
