# Generated by Django 4.2.5 on 2025-03-24 18:48

import articles.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0001_initial'),
        ('monsters', '0013_alter_evolution_from_monster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[articles.validators.MaxLengthValidator(max_length=1024)]),
        ),
        migrations.AlterField(
            model_name='monster',
            name='etymology',
            field=models.TextField(blank=True, null=True, validators=[articles.validators.MaxLengthValidator()]),
        ),
        migrations.CreateModel(
            name='MoveSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster', to='monsters.monster')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move', to='moves.move')),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='moveset',
            field=models.ManyToManyField(blank=True, related_name='monsters', through='monsters.MoveSet', to='moves.move'),
        ),
    ]
