# Generated by Django 4.2.5 on 2025-04-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0014_alter_monster_description_alter_monster_etymology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='avg_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='avg_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
