# Generated by Django 4.2.5 on 2025-04-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0015_alter_monster_avg_height_alter_monster_avg_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='avg_height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='avg_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
