# Generated by Django 4.2.5 on 2025-04-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0016_alter_monster_avg_height_alter_monster_avg_weight'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='evolution',
            index=models.Index(fields=['from_monster', 'to_monster'], name='monsters_ev_from_mo_be266a_idx'),
        ),
        migrations.AddIndex(
            model_name='moveset',
            index=models.Index(fields=['monster', 'move'], name='monsters_mo_monster_c18ea6_idx'),
        ),
    ]
