# Generated by Django 4.2.5 on 2025-06-16 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
        ('monsters', '0017_evolution_monsters_ev_from_mo_be266a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='worlds.world'),
        ),
    ]
