# Generated by Django 4.2.5 on 2025-04-17 21:27

import articles.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0002_article_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True, validators=[articles.validators.MaxLengthValidator(max_length=2048)])),
                ('move_alias', models.CharField(blank=True, default='move', max_length=20)),
                ('course_alias', models.CharField(blank=True, default='technical machine', max_length=20)),
                ('evolution_alias', models.CharField(blank=True, default='evolution', max_length=20)),
                ('monster_alias', models.CharField(blank=True, default='monster', max_length=20)),
                ('ability_alias', models.CharField(blank=True, default='ability', max_length=20)),
                ('level_cap', models.IntegerField(blank=True, default=100)),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='world', to='articles.article')),
            ],
        ),
    ]
