# Generated by Django 4.2.5 on 2026-03-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(blank=True, max_length=10, null=True)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='worlds.world')),
            ],
        ),
    ]
