# Generated by Django 4.2.5 on 2026-04-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0002_stat'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stat',
            index=models.Index(fields=['name', 'world'], name='worlds_stat_name_539687_idx'),
        ),
    ]
