# Generated by Django 4.2.5 on 2023-10-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type_api', '0004_remove_typeadvantage_attacking_type_and_more'),
        ('monster_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='types',
            field=models.ManyToManyField(related_name='regions', to='type_api.type'),
        ),
    ]
