# Generated by Django 4.2.5 on 2024-08-27 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('typings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='typeadvantage',
            name='multiplier',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
