# Generated by Django 4.2.5 on 2024-09-06 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typings', '0003_type_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.DecimalField(decimal_places=1, max_digits=2)),
                ('attacking_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_type', to='typings.type')),
                ('defending_type', models.ManyToManyField(related_name='defending_type', to='typings.type')),
            ],
        ),
        migrations.DeleteModel(
            name='TypeAdvantage',
        ),
    ]
