# Generated by Django 4.2.5 on 2024-09-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typings', '0005_alter_typemodifier_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemodifier',
            name='multiplier',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
