# Generated by Django 4.2.5 on 2024-09-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typings', '0006_alter_typemodifier_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemodifier',
            name='attacking_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_modifiers', to='typings.type'),
        ),
    ]
