# Generated by Django 4.2.5 on 2024-09-06 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typings', '0007_alter_typemodifier_attacking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemodifier',
            name='attacking_type',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, related_name='attack_modifiers', to='typings.type'),
        ),
        migrations.RemoveField(
            model_name='typemodifier',
            name='defending_type',
        ),
        migrations.AddField(
            model_name='typemodifier',
            name='defending_type',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, related_name='defense_modifiers', to='typings.type'),
        ),
    ]
