# Generated by Django 4.2.5 on 2024-09-06 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typings', '0009_alter_typemodifier_attacking_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemodifier',
            name='multiplier',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
    ]
