# Generated by Django 4.2.5 on 2025-02-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typings', '0010_alter_typemodifier_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typemodifier',
            name='multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3),
        ),
    ]
