# Generated by Django 4.2.5 on 2024-01-28 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('damage', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('use_limit', models.IntegerField()),
                ('category', models.CharField(choices=[('PH', 'Physical'), ('SP', 'Special'), ('ST', 'Status')], default='PH', max_length=2, null=True)),
                ('contact', models.BooleanField()),
                ('synergy_description', models.CharField(max_length=300, null=True)),
                ('synergy_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='synergy_moves', to='typings.type')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='typings.type')),
            ],
        ),
    ]
