# Generated by Django 4.2.5 on 2025-03-24 18:52

import articles.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typings', '0011_alter_typemodifier_multiplier'),
        ('articles', '0002_article_date_created'),
        ('moves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='damage',
            new_name='power',
        ),
        migrations.RemoveField(
            model_name='move',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='move',
            name='category',
        ),
        migrations.RemoveField(
            model_name='move',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='move',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='move',
            name='synergy_description',
        ),
        migrations.RemoveField(
            model_name='move',
            name='synergy_type',
        ),
        migrations.RemoveField(
            model_name='move',
            name='use_limit',
        ),
        migrations.AddField(
            model_name='move',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='move', to='articles.article'),
        ),
        migrations.AddField(
            model_name='move',
            name='properties',
            field=models.TextField(blank=True, null=True, validators=[articles.validators.MaxLengthValidator(max_length=2821)]),
        ),
        migrations.AlterField(
            model_name='move',
            name='description',
            field=models.TextField(validators=[articles.validators.MaxLengthValidator()]),
        ),
        migrations.AlterField(
            model_name='move',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='typings.type'),
        ),
    ]
