# Generated by Django 4.2.5 on 2025-03-26 19:55

import articles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0002_rename_damage_move_power_remove_move_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='properties',
            field=models.TextField(blank=True, null=True, validators=[articles.validators.MaxLengthValidator(max_length=2831), django.core.validators.RegexValidator('^{("[a-zA-Z0-9%\\s\\\']{1,20}":\\s("[a-zA-Z0-9%.,;:\\s\\\']{1,256}"),\\s){0,9}("[a-zA-Z0-9%\\s\\\']{1,20}":\\s("[a-zA-Z0-9%.,;:\\s\\\']{1,256}"))}$')]),
        ),
    ]
