# Generated by Django 4.2.5 on 2025-04-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0003_alter_move_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='properties',
        ),
    ]
