# Generated by Django 4.2.5 on 2025-04-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0005_moveproperty_property'),
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='worlds.world'),
        ),
        migrations.AddField(
            model_name='property',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='worlds.world'),
        ),
        migrations.AddField(
            model_name='moveproperty',
            name='move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_properties', to='moves.move'),
        ),
        migrations.AddField(
            model_name='moveproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moves.property'),
        ),
        migrations.AddIndex(
            model_name='moveproperty',
            index=models.Index(fields=['move', 'property'], name='moves_movep_move_id_5b4f56_idx'),
        ),
    ]
