# Generated by Django 4.2.5 on 2026-03-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0006_move_world_property_world_moveproperty_move_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
