# Generated by Django 4.2.5 on 2024-02-26 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_post_who_reposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='who_liked',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='who_reposted',
            field=models.ManyToManyField(blank=True, related_name='reposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
