# Generated by Django 4.2.5 on 2024-02-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_who_liked_alter_post_who_reposted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reposts_count',
        ),
    ]
