# Generated by Django 4.2.5 on 2024-02-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
    ]
