# Generated by Django 4.2.5 on 2024-03-19 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='posts.post'),
        ),
    ]
