# Generated by Django 4.2.5 on 2025-02-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('posts', '0014_post_monster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='post',
            name='monster',
        ),
        migrations.RemoveField(
            model_name='post',
            name='parent_deleted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='who_liked',
        ),
        migrations.RemoveField(
            model_name='post',
            name='who_reposted',
        ),
        migrations.AddField(
            model_name='post',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='articles.article'),
        ),
    ]
