# Generated by Django 4.2.5 on 2025-02-07 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_post_creator_remove_post_monster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
