# Generated by Django 4.2.5 on 2025-02-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_reply',
        ),
    ]
