# Generated by Django 4.2.5 on 2025-02-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_remove_post_is_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted_date',
        ),
    ]
