# Generated by Django 4.2.5 on 2025-03-24 18:48

import articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_remove_post_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True, validators=[articles.validators.MaxLengthValidator(max_length=2048)]),
        ),
    ]
