# Generated by Django 4.2.5 on 2024-05-20 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appuser_bio_appuser_date_joined_appuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='blocking',
            field=models.ManyToManyField(blank=True, related_name='blocked', to=settings.AUTH_USER_MODEL),
        ),
    ]
