# Generated by Django 4.2.5 on 2025-03-24 18:48

import articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appuser_blocking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='bio',
            field=models.TextField(blank=True, default='This is where my bio would go, if I wrote one!', validators=[articles.validators.MaxLengthValidator()]),
        ),
    ]
