# Generated by Django 4.2.5 on 2025-04-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_appuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=35, unique=True),
        ),
    ]
