# Generated by Django 4.2.5 on 2023-10-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('damage', models.IntegerField()),
                ('accuracy', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('use_limit', models.IntegerField()),
                ('category', models.CharField(choices=[('PH', 'Physical'), ('SP', 'Special'), ('ST', 'Status')], default='PH', max_length=2)),
                ('contact', models.BooleanField()),
            ],
        ),
    ]
