# Generated by Django 4.2.5 on 2023-10-07 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type_api', '0001_initial'),
        ('move_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='synergy_description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='move',
            name='synergy_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='synergy_type', to='type_api.type'),
        ),
        migrations.AlterField(
            model_name='move',
            name='category',
            field=models.CharField(choices=[('PH', 'Physical'), ('SP', 'Special'), ('ST', 'Status')], default='PH', max_length=2, null=True),
        ),
    ]
