# Generated by Django 4.2.5 on 2023-10-12 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('type_api', '0004_remove_typeadvantage_attacking_type_and_more'),
        ('move_api', '0004_alter_move_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='synergy_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='synergy_moves', to='type_api.type'),
        ),
        migrations.AlterField(
            model_name='move',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='type_api.type'),
        ),
    ]
