# Generated by Django 4.2.5 on 2025-03-24 18:48

import articles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='effect',
            field=models.TextField(validators=[articles.validators.MaxLengthValidator()]),
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
