# Generated by Django 4.2.5 on 2025-04-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0001_initial'),
        ('abilities', '0002_alter_ability_effect_alter_ability_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='worlds.world'),
        ),
    ]
