# Generated by Django 4.2.5 on 2026-04-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0003_ability_world'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='aura',
            field=models.BooleanField(default=False),
        ),
    ]
