# Generated by Django 4.2.5 on 2025-10-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moves', '0006_move_world_property_world_moveproperty_move_and_more'),
        ('articles', '0002_article_date_created'),
        ('typings', '0012_type_world'),
        ('worlds', '0001_initial'),
        ('monsters', '0018_monster_world'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('map_url', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('article', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='articles.article')),
                ('monsters', models.ManyToManyField(related_name='regions', to='monsters.monster')),
                ('moves', models.ManyToManyField(related_name='regions', to='moves.move')),
                ('types', models.ManyToManyField(related_name='regions', to='typings.type')),
                ('world', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', to='worlds.world')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=300)),
                ('image_description', models.CharField(max_length=300)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='regions.region')),
            ],
        ),
    ]
