# Generated by Django 4.2.5 on 2025-10-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moves', '0006_move_world_property_world_moveproperty_move_and_more'),
        ('typings', '0012_type_world'),
        ('monsters', '0018_monster_world'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='monsters',
            field=models.ManyToManyField(blank=True, related_name='regions', to='monsters.monster'),
        ),
        migrations.AlterField(
            model_name='region',
            name='moves',
            field=models.ManyToManyField(blank=True, related_name='regions', to='moves.move'),
        ),
        migrations.AlterField(
            model_name='region',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='regions', to='typings.type'),
        ),
    ]
