# Generated by Django 4.2.5 on 2023-10-06 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='country',
        ),
    ]
