# Generated by Django 4.2.5 on 2023-10-07 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField()),
                ('attacking_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_type', to='type_api.type')),
                ('defending_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defending_type', to='type_api.type')),
            ],
        ),
    ]
