# Generated by Django 4.2.5 on 2023-10-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('type_api', '0002_type_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typeadvantage',
            old_name='attacking_type_id',
            new_name='attacking_type',
        ),
        migrations.RenameField(
            model_name='typeadvantage',
            old_name='defending_type_id',
            new_name='defending_type',
        ),
    ]
