# Generated by Django 4.2.5 on 2024-01-18 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='likes_count',
        ),
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_repost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 14, 31, 6, 637457)),
        ),
        migrations.AddField(
            model_name='post',
            name='reposts_count',
            field=models.IntegerField(default=0),
        ),
    ]
