# Generated by Django 4.2.5 on 2024-01-18 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_likes_post_likes_count_post_comments_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 20, 35, 34, 73783, tzinfo=datetime.timezone.utc)),
        ),
    ]
